spring.application.name=meta
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://59.110.155.175:3306/
spring.datasource.username=museum_system
spring.datasource.password=123456

# ???? ????????
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl