#Mysql - Common
mysql.db.maxWait=5000
mysql.driverClassName=com.mysql.jdbc.Driver






#dev
mysql.url=jdbc:mysql://115.29.140.80:3306/museum?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
mysql.username=museum
mysql.password=museum123

#prd
#mysql.url=jdbc:mysql://sangularsoft.mysql.rds.aliyuncs.com:3306/yabei-prd?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#mysql.username=yabei_prd
#mysql.password=1qazXSW@

mysql.initialSize=4
mysql.maxActive=20
mysql.maxIdle=8
mysql.minIdle=4

framework.log.level=DEBUG

log.level=DEBUG

# where images store in
fileUpload.fileRootDir=/home/danic/www/museum/

# images relative address, configured in server.xml
fileUpload.fileUrl=/museum-file/